[project]
name = "Age-Matcher"
authors = [
    {name = "Arjun Bingly", email = "arjunbin@gmail.com"},
]
version = '0.0.1'
readme = "README.md"
license = {file = "LICENSE"}

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


